import { Product } from '../components/ProductCard';

export const mockProducts: Product[] = [
  // Electronics
  {
    id: 'e1',
    title: '筆記型電腦 MacBook Air',
    description: '13吋 M1晶片，使用一年，功能正常，附原廠充電器',
    image: 'https://images.unsplash.com/photo-1643290369779-c6bec760cf18?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400&h=300',
    category: 'electronics',
    location: '台北市信義區',
    distance: '0.5km',
    timePosted: '3小時前',
    condition: 'good',
    exchangeType: 'exchange',
    tags: ['筆電', '蘋果', 'MacBook'],
    owner: { name: '陳小明', rating: 4.9 },
    status: 'active',
    views: 156,
    likes: 23
  },
  {
    id: 'e2',
    title: 'iPhone 13 Pro 128GB',
    description: '金色款，購買半年，保護貼和手機殼一直使用',
    image: 'https://images.unsplash.com/photo-1675953935267-e039f13ddd79?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400&h=300',
    category: 'electronics',
    location: '新北市板橋區',
    distance: '1.2km',
    timePosted: '1天前',
    condition: 'like-new',
    exchangeType: 'exchange',
    tags: ['iPhone', '蘋果', '手機'],
    owner: { name: '王大華', rating: 4.7 },
    status: 'active',
    views: 234,
    likes: 45
  },
  {
    id: 'e3',
    title: '無線藍牙耳機 AirPods',
    description: 'AirPods 2代，音質清晰，充電盒功能正常',
    image: 'https://images.unsplash.com/photo-1606400082777-ef05f3c5cde2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400&h=300',
    category: 'electronics',
    location: '台北市大安區',
    distance: '0.8km',
    timePosted: '2天前',
    condition: 'good',
    exchangeType: 'free',
    tags: ['耳機', '蘋果', '藍牙'],
    owner: { name: '李美美', rating: 4.8 },
    status: 'active',
    views: 89,
    likes: 16
  },

  // Books
  {
    id: 'b1',
    title: '商業理財書籍套組',
    description: '包含富爸爸窮爸爸、投資心理學等10本經典理財書',
    image: 'https://images.unsplash.com/photo-1567988122319-039d80fafc34?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400&h=300',
    category: 'books',
    location: '台北市松山區',
    distance: '1.5km',
    timePosted: '4小時前',
    condition: 'good',
    exchangeType: 'exchange',
    tags: ['理財', '投資', '商業'],
    owner: { name: '張志明', rating: 4.6 },
    status: 'active',
    views: 67,
    likes: 12
  },
  {
    id: 'b2',
    title: '兒童繪本大全集',
    description: '適合3-8歲，包含童話故事、科普知識等25本繪本',
    image: 'https://images.unsplash.com/photo-1637195141628-f0f75585a07f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400&h=300',
    category: 'books',
    location: '桃園市中壢區',
    distance: '2.1km',
    timePosted: '1天前',
    condition: 'like-new',
    exchangeType: 'free',
    tags: ['兒童', '繪本', '教育'],
    owner: { name: '林媽媽', rating: 4.9 },
    status: 'active',
    views: 145,
    likes: 28
  },
  {
    id: 'b3',
    title: '程式設計學習書籍',
    description: 'Python、JavaScript入門到進階，共8本技術書籍',
    image: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400&h=300',
    category: 'books',
    location: '台北市內湖區',
    distance: '1.8km',
    timePosted: '3天前',
    condition: 'good',
    exchangeType: 'exchange',
    tags: ['程式', 'Python', 'JavaScript'],
    owner: { name: '程工程師', rating: 4.7 },
    status: 'active',
    views: 98,
    likes: 19
  },

  // Clothing
  {
    id: 'c1',
    title: 'Uniqlo 男裝襯衫組合',
    description: '5件素色襯衫，尺寸M，只穿過幾次，適合上班族',
    image: 'https://images.unsplash.com/photo-1642764873855-934ed87e79e1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400&h=300',
    category: 'clothing',
    location: '台北市中山區',
    distance: '1.1km',
    timePosted: '2小時前',
    condition: 'like-new',
    exchangeType: 'exchange',
    tags: ['襯衫', '男裝', 'Uniqlo'],
    owner: { name: '黃先生', rating: 4.5 },
    status: 'active',
    views: 78,
    likes: 14
  },
  {
    id: 'c2',
    title: '女裝洋裝精選',
    description: '春夏款洋裝3件，尺寸S，品牌包含ZARA、H&M',
    image: 'https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400&h=300',
    category: 'clothing',
    location: '新北市新店區',
    distance: '2.5km',
    timePosted: '1天前',
    condition: 'good',
    exchangeType: 'free',
    tags: ['洋裝', '女裝', 'ZARA'],
    owner: { name: '小雅', rating: 4.8 },
    status: 'active',
    views: 123,
    likes: 25
  },
  {
    id: 'c3',
    title: '運動服飾套組',
    description: 'Nike運動上衣2件+運動褲1件，尺寸L，適合健身',
    image: 'https://images.unsplash.com/photo-1544966503-7cc5ac882d4f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400&h=300',
    category: 'clothing',
    location: '台北市萬華區',
    distance: '1.7km',
    timePosted: '2天前',
    condition: 'good',
    exchangeType: 'exchange',
    tags: ['運動服', 'Nike', '健身'],
    owner: { name: '健身達人', rating: 4.6 },
    status: 'active',
    views: 91,
    likes: 17
  },

  // Furniture
  {
    id: 'f1',
    title: 'IKEA 書桌椅組合',
    description: '白色書桌+人體工學椅子，適合居家辦公或學習',
    image: 'https://images.unsplash.com/photo-1685690227414-07d33378fb59?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400&h=300',
    category: 'furniture',
    location: '台北市士林區',
    distance: '2.3km',
    timePosted: '6小時前',
    condition: 'good',
    exchangeType: 'exchange',
    tags: ['書桌', '椅子', 'IKEA'],
    owner: { name: '搬家族', rating: 4.4 },
    status: 'active',
    views: 167,
    likes: 32
  },
  {
    id: 'f2',
    title: '雙人沙發',
    description: '布質雙人沙發，灰色系，無寵物無煙味，9成新',
    image: 'https://images.unsplash.com/photo-1540574163026-643ea20ade25?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400&h=300',
    category: 'furniture',
    location: '新北市三重區',
    distance: '3.1km',
    timePosted: '1天前',
    condition: 'like-new',
    exchangeType: 'free',
    tags: ['沙發', '雙人', '客廳'],
    owner: { name: '裝潢王', rating: 4.7 },
    status: 'active',
    views: 234,
    likes: 48
  },
  {
    id: 'f3',
    title: '餐桌椅組 4人座',
    description: '實木餐桌+4張椅子，適合小家庭使用',
    image: 'https://images.unsplash.com/photo-1549497538-303791108f95?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400&h=300',
    category: 'furniture',
    location: '台北市北投區',
    distance: '2.8km',
    timePosted: '3天前',
    condition: 'good',
    exchangeType: 'exchange',
    tags: ['餐桌', '實木', '4人座'],
    owner: { name: '木工師傅', rating: 4.9 },
    status: 'active',
    views: 156,
    likes: 29
  },

  // Baby items
  {
    id: 'baby1',
    title: '嬰兒推車 高景觀型',
    description: 'Combi品牌，可坐可躺，輪子靈活，9成新',
    image: 'https://images.unsplash.com/photo-1648691176294-5f92f05654af?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400&h=300',
    category: 'baby',
    location: '台北市文山區',
    distance: '1.4km',
    timePosted: '5小時前',
    condition: 'like-new',
    exchangeType: 'exchange',
    tags: ['推車', '嬰兒', 'Combi'],
    owner: { name: '新手媽媽', rating: 4.8 },
    status: 'active',
    views: 198,
    likes: 36
  },
  {
    id: 'baby2',
    title: '嬰幼兒玩具大禮包',
    description: '適合0-3歲，包含積木、搖鈴、絨毛玩具等15件',
    image: 'https://images.unsplash.com/photo-1572253219988-84dbe0005b86?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400&h=300',
    category: 'baby',
    location: '新北市永和區',
    distance: '1.9km',
    timePosted: '1天前',
    condition: 'good',
    exchangeType: 'free',
    tags: ['玩具', '積木', '嬰幼兒'],
    owner: { name: '三寶媽', rating: 4.6 },
    status: 'active',
    views: 142,
    likes: 28
  },
  {
    id: 'baby3',
    title: '嬰兒床+床墊組合',
    description: '實木嬰兒床，可調節高度，附防撞護欄',
    image: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400&h=300',
    category: 'baby',
    location: '桃園市桃園區',
    distance: '2.6km',
    timePosted: '2天前',
    condition: 'good',
    exchangeType: 'exchange',
    tags: ['嬰兒床', '實木', '床墊'],
    owner: { name: '準爸爸', rating: 4.5 },
    status: 'active',
    views: 178,
    likes: 34
  },

  // Kitchen items
  {
    id: 'k1',
    title: '不鏽鋼鍋具組合',
    description: '德國WMF品牌，包含湯鍋、平底鍋、炒鍋共6件',
    image: 'https://images.unsplash.com/photo-1556910602-38f53e68e15d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400&h=300',
    category: 'kitchen',
    location: '台北市大同區',
    distance: '1.6km',
    timePosted: '3小時前',
    condition: 'like-new',
    exchangeType: 'exchange',
    tags: ['鍋具', 'WMF', '不鏽鋼'],
    owner: { name: '料理達人', rating: 4.9 },
    status: 'active',
    views: 134,
    likes: 26
  },
  {
    id: 'k2',
    title: '小家電組合包',
    description: '電子鍋、烤麵包機、果汁機，功能正常',
    image: 'https://images.unsplash.com/photo-1570222094114-d054a817e56b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400&h=300',
    category: 'kitchen',
    location: '新北市中和區',
    distance: '2.2km',
    timePosted: '1天前',
    condition: 'good',
    exchangeType: 'free',
    tags: ['小家電', '電子鍋', '烤麵包機'],
    owner: { name: '廚房高手', rating: 4.7 },
    status: 'active',
    views: 176,
    likes: 33
  },
  {
    id: 'k3',
    title: '陶瓷餐具套組',
    description: '日式風格，4人份餐具，包含碗盤杯子筷子',
    image: 'https://images.unsplash.com/photo-1578662996442-48f60103fc96?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400&h=300',
    category: 'kitchen',
    location: '台北市中正區',
    distance: '1.3km',
    timePosted: '2天前',
    condition: 'like-new',
    exchangeType: 'exchange',
    tags: ['餐具', '陶瓷', '日式'],
    owner: { name: '和風愛好者', rating: 4.8 },
    status: 'active',
    views: 98,
    likes: 19
  },

  // Automotive
  {
    id: 'a1',
    title: '汽車腳踏墊組合',
    description: '全包圍腳踏墊，適合Toyota Camry，防水材質',
    image: 'https://images.unsplash.com/photo-1758705893982-27c4da18792d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400&h=300',
    category: 'automotive',
    location: '台北市南港區',
    distance: '2.4km',
    timePosted: '4小時前',
    condition: 'good',
    exchangeType: 'exchange',
    tags: ['腳踏墊', 'Toyota', '防水'],
    owner: { name: '老司機', rating: 4.6 },
    status: 'active',
    views: 87,
    likes: 15
  },
  {
    id: 'a2',
    title: '行車記錄器',
    description: '1080P高畫質，夜視功能，已使用1年',
    image: 'https://images.unsplash.com/photo-1517524008697-84bbe3c3fd98?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400&h=300',
    category: 'automotive',
    location: '新北市汐止區',
    distance: '3.2km',
    timePosted: '1天前',
    condition: 'good',
    exchangeType: 'free',
    tags: ['行車記錄器', '1080P', '夜視'],
    owner: { name: '安全駕駛', rating: 4.4 },
    status: 'active',
    views: 156,
    likes: 29
  },
  {
    id: 'a3',
    title: '汽車充電器組合',
    description: 'USB充電器+車用手機支架，適合各種車型',
    image: 'https://images.unsplash.com/photo-1549488344-cbb064c71da8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400&h=300',
    category: 'automotive',
    location: '台北市木柵區',
    distance: '2.7km',
    timePosted: '3天前',
    condition: 'like-new',
    exchangeType: 'exchange',
    tags: ['充電器', 'USB', '手機支架'],
    owner: { name: '科技男', rating: 4.7 },
    status: 'active',
    views: 112,
    likes: 21
  },

  // Toys & Games
  {
    id: 't1',
    title: '樂高積木大禮包',
    description: '城市系列+創意系列，包含警察局、消防局等5盒',
    image: 'https://images.unsplash.com/photo-1566327177044-45e319f8cffa?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400&h=300',
    category: 'toys',
    location: '台北市信義區',
    distance: '1.8km',
    timePosted: '2小時前',
    condition: 'like-new',
    exchangeType: 'exchange',
    tags: ['樂高', '積木', '城市系列'],
    owner: { name: '樂高迷', rating: 4.9 },
    status: 'active',
    views: 245,
    likes: 47
  },
  {
    id: 't2',
    title: '桌遊收藏組合',
    description: '大富翁、UNO、拉密等經典桌遊共8款',
    image: 'https://images.unsplash.com/photo-1611371805429-8b5c1b2c34ba?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400&h=300',
    category: 'toys',
    location: '新北市淡水區',
    distance: '2.9km',
    timePosted: '1天前',
    condition: 'good',
    exchangeType: 'free',
    tags: ['桌遊', '大富翁', 'UNO'],
    owner: { name: '桌遊達人', rating: 4.8 },
    status: 'active',
    views: 187,
    likes: 35
  },
  {
    id: 't3',
    title: '遙控飛機',
    description: '四軸無人機，附攝影鏡頭，適合戶外飛行',
    image: 'https://images.unsplash.com/photo-1507808073436-efe19e72e2fd?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400&h=300',
    category: 'toys',
    location: '台北市松山區',
    distance: '1.5km',
    timePosted: '2天前',
    condition: 'good',
    exchangeType: 'exchange',
    tags: ['無人機', '遙控', '攝影'],
    owner: { name: '飛行員', rating: 4.6 },
    status: 'active',
    views: 198,
    likes: 38
  }
];

// 體育運動類別的額外商品
export const sportsProducts: Product[] = [
  {
    id: 's1',
    title: '瑜珈墊+運動用品組',
    description: '專業瑜珈墊、瑜珈磚、彈力帶等健身用品',
    image: 'https://images.unsplash.com/photo-1652492041264-efba848755d6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400&h=300',
    category: 'sports',
    location: '台北市大安區',
    distance: '1.1km',
    timePosted: '3小時前',
    condition: 'good',
    exchangeType: 'exchange',
    tags: ['瑜珈', '健身', '運動'],
    owner: { name: '瑜珈老師', rating: 4.8 },
    status: 'active',
    views: 134,
    likes: 26
  },
  {
    id: 's2',
    title: '籃球+運動鞋',
    description: 'Spalding籃球+Nike籃球鞋(US9)，適合戶外運動',
    image: 'https://images.unsplash.com/photo-1546519638-68e109498ffc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400&h=300',
    category: 'sports',
    location: '新北市板橋區',
    distance: '2.3km',
    timePosted: '1天前',
    condition: 'good',
    exchangeType: 'free',
    tags: ['籃球', 'Nike', '運動鞋'],
    owner: { name: '籃球高手', rating: 4.7 },
    status: 'active',
    views: 167,
    likes: 31
  }
];